### ISSUE TITLE
Merancang Gambaran desain awal web

### ISSUE THREAD

**Issue by pieterch7** [pieterch7/uas_manajemenprojek#16]
Desain ini akan digunakan untuk gambaran awal sehingga nanti bisa diimplementasikan

**Comment by felixwiranata1233** [comment]
[desainawal.pdf](https://github.com/pieterch7/uas_manajemenprojek/files/13802801/desainawal.pdf)

ini gambaran desain awal saya mungkin bisa digunakan

**Comment by stevenval12** [comment]
oke siap

**Comment by pieterch7** [comment]
oke nanti kita menggunakan file diatas sebagai patokannya
