### ISSUE TITLE
Membuat Tempat untuk berkumpul

### ISSUE THREAD

**Issue by pieterch7** [pieterch7/uas_manajemenprojek#17]

**Comment by felixwiranata1233** [comment]
kira kira mau pakai aplikasi apa untuk berkumpul member?

**Comment by pieterch7** [comment]
kemungkinan kita akan menggunakan wa/telegram

**Comment by felixwiranata1233** [comment]
sepertinya tampilan telegram lebih nyaman digunakan

**Comment by pieterch7** [comment]
oke kalau begitu saya akan menggunakan telegram
