### ISSUE TITLE
Menemukan Bug

### ISSUE THREAD

**Issue by pieterch7** [pieterch7/uas_manajemenprojek#21]

**Comment by felixwiranata1233** [comment]
tadi saya menemukan link instagram yang tidak bisa diklik

**Comment by pieterch7** [comment]
oke bisa langsung di perbaiki

**Comment by felixwiranata1233** [comment]
dan ada satu link yang tidak bisa diklik yaitu link facebook

**Comment by pieterch7** [comment]
oke sudah diperbaiki semuanya
